spring:
  profiles:
    active: app
  cloud:
    stream:
      kafka:
        binder:
          consumerProperties:
            max.poll.interval.ms:  ${KAFKA_CONSUMER_MAX_POLL_INTERVAL:300000}
            max.poll.records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:100}